name: Buil wallet sdk

on:
  push:
    branches: ["feature/github-action"]

jobs:
  build-ios:
    name: build wallet sdk for iOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Set up go mobile
        run: |
          go get golang.org/x/mobile/cmd/gomobile
          go get golang.org/x/mobile/bind
      - name: Set up git context
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git clone git@github.com:coming-chat/wallet-swift-package.git Wallet-iOS
          git clone git@github.com:coming-chat/wallet-sdk-android.git
      - name: Build iOS sdk & push
        run: |
          export GOPRIVATE=github.com/coming-chat/go-defi-sdk && make iosBuildAndPublish v=test-0.0.1
