name: Buil wallet sdk

on:
  push:
    branches: ["feature/github-action"]

jobs:
  build-ios:
    name: build wallet sdk for iOS
    runs-on: macos-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Set up git context
        uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          global: true
          name: "github-actions[bot]"
          email: "41898282+github-actions[bot]@users.noreply.github.com"
          actor: "github-actions[bot]"
          token: "${{ secrets.GIT_TOKEN }}"
      - name: Set up go mobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up iOS package repo
        run: |
          git clone https://github.com/coming-chat/wallet-swift-package.git Wallet-iOS
      - name: Build iOS sdk & push
        run: |
          export GOPRIVATE=github.com/coming-chat/go-defi-sdk && make iosBuildAndPublish v=test-0.0.1
